version: '3.8'

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
 
volumes:
    db:
